/**
 * Claude API Client for Security Analysis
 *
 * Provides Claude API integration for:
 * - Product categorization (Phase 1 of CVE synthesis)
 * - Security check synthesis (Phase 2 of CVE synthesis)
 * - Runtime code security analysis
 */

import Anthropic from '@anthropic-ai/sdk';

// Initialize client - uses ANTHROPIC_API_KEY env var by default
let client: Anthropic | null = null;

function getClient(): Anthropic {
    if (!client) {
        const apiKey = process.env.ANTHROPIC_API_KEY;
        if (!apiKey) {
            throw new Error(
                'ANTHROPIC_API_KEY environment variable is required.\n' +
                'Set it with: export ANTHROPIC_API_KEY=your-api-key'
            );
        }
        client = new Anthropic({ apiKey });
    }
    return client;
}

/**
 * Configuration for Claude API calls
 */
export interface ClaudeConfig {
    model?: string;
    maxTokens?: number;
    temperature?: number;
}

const DEFAULT_CONFIG: Required<ClaudeConfig> = {
    model: 'claude-sonnet-4-20250514',
    maxTokens: 8192,
    temperature: 0.3,  // Lower temperature for more consistent structured output
};

/**
 * Make a Claude API call with the given prompt
 */
export async function callClaude(
    prompt: string,
    systemPrompt?: string,
    config: ClaudeConfig = {}
): Promise<string> {
    const anthropic = getClient();
    const finalConfig = { ...DEFAULT_CONFIG, ...config };

    const message = await anthropic.messages.create({
        model: finalConfig.model,
        max_tokens: finalConfig.maxTokens,
        temperature: finalConfig.temperature,
        system: systemPrompt,
        messages: [
            { role: 'user', content: prompt }
        ]
    });

    // Extract text from response
    const textBlock = message.content.find(block => block.type === 'text');
    if (!textBlock || textBlock.type !== 'text') {
        throw new Error('No text response from Claude');
    }

    return textBlock.text;
}

/**
 * Call Claude and parse JSON response
 */
export async function callClaudeForJSON<T>(
    prompt: string,
    systemPrompt?: string,
    config: ClaudeConfig = {}
): Promise<T> {
    const response = await callClaude(prompt, systemPrompt, config);

    // Extract JSON from response (handle markdown code blocks)
    let jsonStr = response;

    // Try to extract from ```json ... ``` block
    const jsonMatch = response.match(/```(?:json)?\s*([\s\S]*?)```/);
    if (jsonMatch) {
        jsonStr = jsonMatch[1].trim();
    }

    try {
        return JSON.parse(jsonStr) as T;
    } catch (error) {
        // If parsing fails, try to find JSON object/array in response
        const objectMatch = response.match(/\{[\s\S]*\}/);
        const arrayMatch = response.match(/\[[\s\S]*\]/);

        if (objectMatch) {
            return JSON.parse(objectMatch[0]) as T;
        } else if (arrayMatch) {
            return JSON.parse(arrayMatch[0]) as T;
        }

        throw new Error(`Failed to parse JSON from Claude response: ${error}`);
    }
}

/**
 * Product category as generated by the LLM
 */
export interface ProductCategory {
    name: string;
    description: string;
    products: string[];
    codeSignals: string[];
}

/**
 * Categorization response from LLM
 */
export interface CategorizationResponse {
    categories: Record<string, ProductCategory>;
}

/**
 * Security check as generated by the LLM
 */
export interface GeneratedSecurityCheck {
    id: string;
    title: string;
    checkPrompt: string;
    whyItMatters: string;
    severity: 'critical' | 'high' | 'medium' | 'low';
    codeSignals: string[];
    basedOnCVEs?: string[];
}

/**
 * Synthesis response from LLM
 */
export interface SynthesisResponse {
    category: string;
    categoryName: string;
    securityChecks: GeneratedSecurityCheck[];
    generalPrinciples: string[];
}

/**
 * Call Claude to categorize products into generic types
 */
export async function categorizeProducts(
    categorizationPrompt: string
): Promise<CategorizationResponse> {
    const systemPrompt = `You are a security expert categorizing software products for vulnerability analysis.
Your goal is to map specific products (Apache, nginx, MySQL) to GENERIC categories (web server, database)
that a code reviewer could identify when looking at any codebase.

Return valid JSON only. Do not include any explanation outside the JSON.`;

    return callClaudeForJSON<CategorizationResponse>(
        categorizationPrompt,
        systemPrompt,
        { maxTokens: 16384 }  // Larger for potentially many products
    );
}

/**
 * Call Claude to synthesize security checks from CVEs
 */
export async function synthesizeSecurityChecks(
    synthesisPrompt: string
): Promise<SynthesisResponse> {
    const systemPrompt = `You are a security expert analyzing CVE vulnerability data to create actionable security review prompts.
Focus on patterns that appear across MULTIPLE CVEs - these are the most important checks.
Create prompts that apply to ANY code of this type, not specific products.

Return valid JSON only. Do not include any explanation outside the JSON.`;

    return callClaudeForJSON<SynthesisResponse>(
        synthesisPrompt,
        systemPrompt,
        { maxTokens: 16384, temperature: 0.4 }
    );
}

/**
 * Code analysis finding from Claude
 */
export interface SecurityFinding {
    location: {
        file?: string;
        startLine: number;
        endLine: number;
        codeSnippet: string;
    };
    vulnerabilityType: {
        cweId?: number;
        name: string;
        category: string;
    };
    severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
    description: string;
    remediation: string;
    confidence: 'HIGH' | 'MEDIUM' | 'LOW';
}

/**
 * Code analysis response from Claude
 */
export interface CodeAnalysisResponse {
    findings: SecurityFinding[];
    summary: string;
    securityPosture: 'CRITICAL' | 'CONCERNING' | 'MODERATE' | 'GOOD';
}

/**
 * Analyze code for security vulnerabilities using Claude
 */
export async function analyzeCodeSecurity(
    code: string,
    language: string,
    securityChecks: GeneratedSecurityCheck[],
    fileName?: string
): Promise<CodeAnalysisResponse> {
    const checksFormatted = securityChecks.map(check =>
        `### ${check.title} (${check.severity.toUpperCase()})\n${check.checkPrompt}\n**Why it matters:** ${check.whyItMatters}`
    ).join('\n\n');

    const prompt = `# Security Code Review

## Code to Analyze
**File:** ${fileName || 'unknown'}
**Language:** ${language}

\`\`\`${language}
${code}
\`\`\`

## Security Checks to Perform

${checksFormatted}

## Instructions

Analyze the code above for security vulnerabilities based on the security checks provided.
For each vulnerability found, provide detailed information.

Return your analysis as JSON in this exact format:
\`\`\`json
{
  "findings": [
    {
      "location": {
        "startLine": 10,
        "endLine": 12,
        "codeSnippet": "the vulnerable code"
      },
      "vulnerabilityType": {
        "cweId": 89,
        "name": "SQL Injection",
        "category": "injection"
      },
      "severity": "HIGH",
      "description": "What the vulnerability is and why it's dangerous",
      "remediation": "Specific fix with code example",
      "confidence": "HIGH"
    }
  ],
  "summary": "Brief overall assessment",
  "securityPosture": "CONCERNING"
}
\`\`\`

If no vulnerabilities are found, return an empty findings array and explain what security measures are in place in the summary.`;

    const systemPrompt = `You are an expert security code reviewer. Analyze code thoroughly for vulnerabilities.
Be precise about line numbers and provide actionable remediation.
Only report real vulnerabilities - avoid false positives.
Return valid JSON only.`;

    return callClaudeForJSON<CodeAnalysisResponse>(
        prompt,
        systemPrompt,
        { maxTokens: 8192, temperature: 0.2 }
    );
}

/**
 * Check if Claude API is available
 */
export function isClaudeAvailable(): boolean {
    return !!process.env.ANTHROPIC_API_KEY;
}

/**
 * Get information about Claude configuration
 */
export function getClaudeInfo(): {
    available: boolean;
    model: string;
    message: string;
} {
    const available = isClaudeAvailable();
    return {
        available,
        model: DEFAULT_CONFIG.model,
        message: available
            ? `Claude API available (model: ${DEFAULT_CONFIG.model})`
            : 'Claude API not configured. Set ANTHROPIC_API_KEY environment variable.'
    };
}
